image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.13.2\msvc2017
  - set MAKE=C:\Qt\Tools\QtCreator\bin\jom.exe
  - set VCVARS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  - set VCREDIST_DLL=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.16.27012\x86\Microsoft.VC141.CRT
  - set VCREDIST_MSM=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.16.27012\MergeModules\Microsoft_VC141_CRT_x86.msm
  - set WIXDIR=C:\Program Files (x86)\WiX Toolset v3.11\bin
  - set OPENSSL=C:\OpenSSL-v111-Win32\bin
  - set SEVENZIP=7z
  - C:\Python37\python scripts\download.py

before_build:
  - cd scripts\win32\packages

build_script:
  - call msi/build.msi.bat
  - call zip/build.zip.bat

artifacts:
  - path: scripts\win32\packages\msi\wix\bin\apk-editor-studio_win32_dev.msi
    name: APK Editor Studio - Windows Installer (MSI)
  - path: scripts\win32\packages\zip\apk-editor-studio_win32_dev.zip
    name: APK Editor Studio - Windows Portable (ZIP)

deploy:
  - provider: GitHub
    tag: development
    release: Developer Build
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: F4j34oc5G2EocYZKQVCbPpEM3wH9h20rCsQ8WhSHZ5dlg2SqtRDmQi13+CScmhYn
