install:
  - set QTDIR=C:\Qt\5.11\msvc2015
  - set OPENSSL=C:\OpenSSL-Win32\bin
  - set VCDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  - set VCREDIST=%VCDIR%\redist\x86\Microsoft.VC140.CRT
  - set WIXDIR=C:\Program Files (x86)\WiX Toolset v3.11\bin
  - set SEVENZIP=7z
  - set VERSION=dev

before_build:
  - cd scripts\win32\packages

build_script:
  # TODO Matrix
  - call msi/build.msi.bat
  - call zip/build.zip.bat

artifacts:
  - path: scripts\win32\packages\msi\wix\bin\apk-editor-studio_win32_dev.msi
    name: APK Editor Studio - Windows Installer (MSI)
  - path: scripts\win32\packages\zip\apk-editor-studio_win32_dev.zip
    name: APK Editor Studio - Windows Portable (ZIP)

deploy:
  - provider: GitHub
    tag: development
    release: Developer Build
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: F4j34oc5G2EocYZKQVCbPpEM3wH9h20rCsQ8WhSHZ5dlg2SqtRDmQi13+CScmhYn
